<a href="https://colab.research.google.com/github/CHOOSLA/Self_Studying_of_Machine-Learning_and_Deep-Learning/blob/main/Chapter_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#로지스틱 회귀

#럭키백 만들기
#럭키백은 구성품을 모른채 먼저 구매하고, 배송받은 다음에야 비로소 구성품을 알 수 잇는 상품입니다.

#럭키백의 확률
#럭키백에 들어갈 수 있는 생선은 7개
#이번에는 길이 , 높이 , 두께 외에도 대각선 길이와 무게도 사용할 수 있다.


#데이터 준비하기
import pandas as pd
fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head() #처음 5개의 행을 출력

print(pd.unique(fish['Species'])) #Species 값에서 고유한 값을 뽑아냄


#여기서 species 열을 타깃으로 만들고 나머지는 입력데이터로 만들겠다
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
print(fish_input[:5])

fish_target = fish['Species'].to_numpy()

from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(fish_input,fish_target,random_state=42)

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)


#최근접 이웃 분류기의 확률 예측
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled,train_target)
print(kn.score(train_scaled,train_target))
print(kn.score(test_scaled,test_target))

#2개 이상의 클래스가 포함된 문제를 다중 분류 ( 정답이 2개이상일 때 )
print(kn.classes_) #정답인 것을 출력함 알아서 알파벳 순으로 매겨집니다

print(kn.predict(test_scaled[:5]))

#예측은 어떤 확률로 만들어 졌을 까요?
#사이킷 분류 모델은 predict_proba() 메서드로 클래스별 확률값을 반환합니다

import numpy as np
proba = kn.predict_proba(test_scaled[:5])
print(np.round(proba,decimals=4)) #소수점 네 번째 자리 까지 표시 decimals

distances , indexes = kn.kneighbors(test_scaled[3:4])
print(train_target[indexes])

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]
0.8907563025210085
0.85
['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']
[[0.     0.     1.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     1.     0.     0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]]
[['Roach' 'Perch' 'Perch']]
